#! /bin/bash

# ############ Env vars used, set in Codeship#####################################################
# AWS_ACCESS_KEY=$AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

# AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
# AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
# CLUSTER_NAME=$CLUSTER_NAME
# SERVICE_BASENAME=$SERVICE_BASENAME
# #   (i.e. my-app; -dev will get appended for the dev environment, making my-app-dev)
# IMAGE_BASENAME=$IMAGE_BASENAME
# #   (i.e. my-app; -dev will get appended for the dev environment, making my-app-dev)

# ## Env vars generated by Codeship
# CI_BRANCH=$CI_BRANCH
# CI_COMMIT_ID=$CI_COMMIT_ID
# CI_PULL_REQUEST=$CI_PULL_REQUEST
# ################################################################################################

pushToEcr () {
    eval $(aws ecr get-login --region $AWS_DEFAULT_REGION)
        
    echo "Pushing $2 to $1"
    docker tag $2 $1
    docker push $1
    echo "Pushed $1"

    # for tag in {16.04,latest}; do  
    #   docker tag $IMAGE_NAME ${IMAGE_BASENAME}:${tag}
    #   docker push ${IMAGE_BASENAME}:${tag}
    # done 

}

if [ -z "$CI_PULL_REQUEST" ] || [ "$CI_PULL_REQUEST" == "false" ]; then

    ENV_SUFFIX="-demo"
    if [ "$CI_BRANCH" == "master" ]; then 
      ENV_SUFFIX="-demo"
    elif [ "$CI_BRANCH" == "staging" ]; then 
      ENV_SUFFIX="-stg"
    elif [ "$CI_BRANCH" == "production" ]; then 
      ENV_SUFFIX="-prod"
    else 
      return 0;  
    fi

    IMAGE_FULLNAME=$IMAGE_BASENAME$ENV_SUFFIX
    IMAGE_URL=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_BASENAME:$CI_COMMIT_ID
    SERVICE_FULLNAME=$SERVICE_BASENAME$ENV_SUFFIX

    pushToEcr $IMAGE_URL $IMAGE_FULLNAME
    
    echo "Deploying $CI_BRANCH on service $SERVICE_FULLNAME"
    deploy-ecs/ecs-deploy.sh -c $CLUSTER_NAME -n $SERVICE_FULLNAME -i $IMAGE_URL -r $AWS_DEFAULT_REGION
fi 